### ISSUE TITLE
Custom Workflow not producing events

### ISSUE THREAD

**Issue by SimonGurney** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#14]
I have written a custom Workflow for Idaptive events and it returns 5 events when I click "Test" in the LSM however when deployed it never returns an event.  

I ran it on the command line and the events are returned in their hundreds.

Any idea why it would not collect events?  Is there a log I should look in?

**Comment by CH-KeithMo** [comment]
@kdegrace Feel free to remove this if I am breaking rules.

@SimonGurney You can try the command line test as well.  Maybe there is something we are missing here.  I am just beginning in my Cloud API testing with a few various sources (hope to have pull requests or forks or whatnot, uploaded soon)

```
Example:# 
java -cp "/opt/ibm/si/services/ecs-ec-ingress/current/bin/*:/opt/ibm/si/services/ecs-ec-ingress/eventgnosis/lib/q1labs/*" com.q1labs.semsources.sources.universalcloudrestapi.UniversalCloudRESTAPITest -w myworkflow.xml -wp myworkflow.parameter.values.xml
```

**Comment by SimonGurney** [comment]
Thanks @CH-KeithMo 

Sorry this is what I meant by "I ran it on the command line and the events are returned in their hundreds.".

It looks like most events were being indexed without a source and I had to configure some parsing.  This is a bit confusing to me as the sourcetype is configured in LSM.  

There still seems to be some discrepency with what gets returned on the commandline and what gets ingested.  Is there a log to check which would show how many events etc are coming from the workflow or some way to view the current state?

**Comment by kdegrace** [comment]
Most uses of this protocol will require some additional work in the DSM Editor to create a Custom DSM for the events.

In QRadar's Log Activity, if you filter on this log source, you see no events at all?

**Comment by SimonGurney** [comment]
Thanks for the response.  I added some logging into the Workflow which then output into /var/log/qradar.log and showed me that an issue in the code meant my bookmark was getting ahead of now and therefore always yielding 0 events after a while.  Maybe the use of the Log command, and checking /var/log/qradar.log, should be added to the README for troubleshooting?  It would have saved me some time.

**Comment by kdegrace** [comment]
Good idea, thanks.  I will make note to add a troubleshooting section with some tips and tricks.
