### ISSUE TITLE
Need to drop null keys

### ISSUE THREAD

**Issue by SimonGurney** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#16]
The REST endpoint I am working with at the moment (JSON) returns a lot a keys with the value set to "null".  Rather than having to define all the key names, is it possible to selectively drop dict elements if the value is null (or some other arbitrary condition")?

Consider the following.  I would want to remove all keys with a "null" value.  I tried to foreach through but this only works for arrays.

{
   "Result":{
      "a":null,
      "b":"null",
      "c":"some_string"
   }
}

It is common for APIs to return empty fields, using some mechanism to suggest they are empty such as "unknown" "na" etc so this is a likely requirement for a lot of endpoints.

**Comment by kdegrace** [comment]
There is currently no way to iterate object keys.  The only way to accomplish this would be to have code very specific to each field.

e.g.
```
        <If condition="/Result/a = null or /Result/a = 'null'">
            <Delete path="/Result/a" />
        </If>

        <If condition="/Result/b = null or /Result/b = 'null'">
            <Delete path="/Result/b" />
        </If>

        <If condition="/Result/c = null or /Result/c = 'null'">
            <Delete path="/Result/c" />
        </If>
```

**Comment by kdegrace** [comment]
The other option would be to do it in the Custom DSM. I believe there are mechanisms available there to filter based on values, e.g. Property Discovery and Property Filter Classes. But again, these would be very specific to the data.  Nothing that would just generically iterate the fields and apply some conditional logic.

**Comment by SimonGurney** [comment]
Thanks.  I thought this was the case.

Unfortunately those two workarounds would not work in this scenario as the fields could change at any point and introduce breaking changes or make maintenance labour intensive.  It would be good to see this implemented as a feature maybe, either allowing key iteration or a JPATH query function to filter directly.

**Comment by kdegrace** [comment]
I've created an internal work item to update ForEach so it can accept a JSON object, and will iterate over its keys.

So you'd be able to do something like this:
```
        <ForEach items="/Result" item="/current_key">
            <If condition="/Result/${/current_key} = null or /Result/${/current_key} = 'null'">
                <Delete path="/Result/${/current_key}" />
            </If>
        </ForEach>
```

or something like this:
```
        <ForEach items="/Result" item="/current_key">
            <If condition="/Result/${/current_key} != null and /Result/${/current_key} != 'null'">
                <Set path="/TrimmedResult/${/current_key}" value="${/Result/${/current_key}}"/>
            </If>
        </ForEach>
```

**Comment by SimonGurney** [comment]
That would be perfect.  I ad already written the first example before realising it was only currently for Arrays.

Any idea on timescale to implement?

**Comment by kdegrace** [comment]
It's unclear when we will release the next version of the protocol. I already implemented the change but now it is a process to get it tested, etc.  I'll update when I know more.

**Comment by sqa-consulting** [comment]
I have just implemented the Duo workflow (not mine) and it has the same issue FYI.

Example snip of a log 

"browser":null,"browser_version":null,"flash_version":null,"java_version":null,"os":null,"os_version":null}...

**Comment by SimonGurney** [comment]
Hi @kdegrace, any update on this?

**Comment by kdegrace** [comment]
Hi Simon, a new version of this protocol has been released on FixCentral which now allows you to iterate over the fields of a JSON object (as described in the previous comments here).  You'll have to reference V2 in the xmlns attribute of the Workflow to use the new features:
e.g.
`xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/Workflow/V2"`

The online documentation for the protocol has also been updated with the new features in this version.
https://www.ibm.com/docs/en/dsm?topic=configuration-universal-cloud-rest-api-protocol
