### ISSUE TITLE
New Workflow:  Sophos Cloud 

### ISSUE THREAD

**Issue by CH-KeithMo** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#21]
Per Contributing.md, I am just making this issue request so that I (or we) can track the status on ingesting Sophos Cloud.  Just going to paste some supporting documentation that I have found so far.

https://developer.sophos.com/intro

https://news.sophos.com/en-us/2019/12/19/unlocking-the-power-of-sophos-central-api/
(This is the SIEM integration python script, but may be useful)

EDIT:  This is very early stages and I do not have any working XML yet.  I have only confirmed that I can get an API Token using the customer provided API Keys.

**Comment by sivaranjinipanneerselvam** [comment]
Hello Keith,

Below are the Pull request submitted for Sophos,
https://github.com/ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API/pull/53
https://github.com/ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API/pull/54

I have tested the workflow and it works as expected.
Please free to let know for any further clarity.

**Comment by ChrisCollinsIBM** [comment]
Previously merged
