### ISSUE TITLE
Prisma Cloud API  - Body exceeds the currently supported maximum of 100 MB

### ISSUE THREAD

**Issue by plamenpanov** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#22]
Hi folks,
I'm from IBM Qradar support and we are seeing the following issue when attempting a log collection from Prisma Cloud API.
"Body exceeds the currently supported maximum of 100 MB"

So I'm following the advise of the developers bellow:
----
En Zhang added a comment - 24/Nov/20 9:24 PM
Looks like the pagination is not implemented in the workflow xml, which is supported by the protocol. 
Please open a ticket on github for Keith to follow up with that and leave a comment/link here after to track the issue from the support perspective in the future.
---

Kind regards,
Plamen Panov
Qradar support

**Comment by kdegrace** [comment]
The data will now be fetched in pages of 50 events at a time which should avoid this body size limitation.

**Comment by plamenpanov** [comment]
Thanks for implementing that Keith,
I will inform the customer.
