### ISSUE TITLE
Oracle Cloud

### ISSUE THREAD

**Issue by rushkylj** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#26]
Seeing if anyone on here has seen or worked on anything related to Oracle Cloud yet. I'm new to this Cloud Rest API DSM, so not sure where to start on the workflow.  Appreciate any input!

**Comment by ChrisCollinsIBM** [comment]
Oracle Cloud is a pretty wide topic, we're adding support for Cloud Object Storage in Oracle in the near future in the regular QRadar protocols so look out for that!
