### ISSUE TITLE
IBM Cloud LogDNA for IBM Cloud VPC Logs

### ISSUE THREAD

**Issue by mdobbsatl** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#30]
Creating a workflow for working with IBM Cloud LogDNA instance. The IBM Cloud LogDNA needs a couple of changes from the current LogDNA workflow. IBM Cloud LogDNA uses a servicekey instead of username and password for the REST API calls.

I would also like to include some additional query parameters for limiting the types of logs returned for QRadar to ingest.

**Comment by ChrisCollinsIBM** [comment]
When you have a workflow please re-open this or submit a new issue along with the Pull Request. Thanks!
