### ISSUE TITLE
Creating a Cisco Webex Restapi Connection

### ISSUE THREAD

**Issue by StevenBeck93** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#34]
Hello,

at the moment i try to create a connection to Cisco Webex Restapi.

But in IBM QRadar i get a Log Source Test Error:

Not a JSON Array: {"items":[{"id":"Y2lzY29zcGFyazovL3VzL0VWRU5ULzE2Zjk1N ....

Is there anyone who can help?

My Code:

<?xml version="1.0" encoding="UTF-8" ?>
<Workflow name="Webex" version="1.0" xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/Workflow/V1">

    <Parameters>
        <Parameter name="access_token" label="Access Token" required="true" default="*secret*" />
		<Parameter name="host" label="Host" required="true" default="webexapis.com" />
    </Parameters>

    <Actions>

        
        <Initialize path="/bookmark" value="2021-02-25T00:00:00.000Z" />

        
        <CallEndpoint url="https://${/host}/v1/events/" method="GET" savePath="/get_events">
            <BearerAuthentication token="${/access_token}" />
            <QueryParameter name="from" value="2021-02-25T00:00:00.000Z" omitIfEmpty="true" />
			<QueryParameter name="resource" value="memberships" omitIfEmpty="true" />
			<QueryParameter name="max" value="10" omitIfEmpty="true" />
        </CallEndpoint>

        
        <If condition="/get_events/status_code != 200">
            <Abort reason="${/get_events/body/code}: ${/get_events/body/message}" />
        </If>
        
		
        <If condition="count(/get_events/body) > 0">
		
            <PostEvents path="/get_events/body" source="${/host}" />

            
            
            

        </If>
		

    </Actions>

    <Tests>
        <DNSResolutionTest host="${/host}" />
        <TCPConnectionTest host="${/host}" />
        <SSLHandshakeTest host="${/host}" />
        <HTTPConnectionThroughProxyTest url="https://${/host}" />
    </Tests>

</Workflow>

**Comment by keith-degrace** [comment]
I assume it's coming from this line:
`<PostEvents path="/get_events/body" source="${/host}" />`

Try this:
`<PostEvents path="/get_events/body/items" source="${/host}" />`

**Comment by ajeeshneelamkavil** [comment]
also try <PostEvents path="/get_logs/body/result" source="${/host}"/>

**Comment by ChrisCollinsIBM** [comment]
Hi @StevenBeck93, did you get things working ok or do you still need assistance?

**Comment by ChrisCollinsIBM** [comment]
Closing out as this seems to be stale. But please re-open if you still need assistance. Thanks.
