### ISSUE TITLE
Duo: Invalid Signature in request credentials.

### ISSUE THREAD

**Issue by CH-KeithMo** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#37]
Error when testing Log Source:

40103: Invalid signature in request credentials

It seems like something has changed here.  I used to have this working for other customers.  When re-creating my Duo log source, I get this error for new setups.  Existing setups also seem to fail to get ~~Normal~~ Auth events (we only get Admin events).

https://community.duo.com/t/error-40103-invalid-signature-in-request-credentials-on-calls-with-no-parameters/8193

I tried to make a few changes here and there with no luck.

Edit:

I just tried to feed ym XMLs into the debug testing at command line and it worked fine.  I am honestly lost on what is going on here.

**Comment by ChrisCollinsIBM** [comment]
So it's working from the command-line tool for you but not as a running workflow?

**Comment by ChrisCollinsIBM** [comment]
Does your call have the parameters and they are empty? Or it's not passing the parameters at all?

This section of the Duo workflow is specifically around generating the HMAC signature.

` 
        <FormatDate pattern="EEE, dd MMM yyyy HH:mm:ss Z" timeZone="UTC" savePath="/auth_logs/date" />
        <Set path="/value" value="${/auth_logs/date}&#xA;GET&#xA;${/host}&#xA;/admin/v1/logs/authentication&#xA;mintime=${/auth_logs/bookmark}" />
        <GenerateHMAC algorithm="SHA1" secretKey="${/secret_key}" message="${/value}" saveFormat="HEX" savePath="/signature" />`

Which roughly decodes to
```
${/auth_logs/date}
GET
${/host}
/admin/v1/logs/authentication
mintime=${/auth_logs/bookmark}
```

So if the parameters were empty I think you'd still need

${/auth_logs/date}&#xA;GET&#xA;${/host}&#xA;/admin/v1/logs/authentication&#xA;

```
${/auth_logs/date}
GET
${/host}
/admin/v1/logs/authentication

```

Which makes the blank line at the end. Did you try that?

**Comment by ChrisCollinsIBM** [comment]
Just wanted to followup on your question @CH-KeithMo - did you have a chance to look at my response?

**Comment by ChrisCollinsIBM** [comment]
Hi @CH-KeithMo, I'm closing this out for now as we haven't heard back, but please re-open if the issue persists.
