### ISSUE TITLE
Add the workflow for the Google G Suite 

### ISSUE THREAD

**Issue by Abrar729** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#47]
We are working to collect the G Suite Gmail logs since G suite Gmail Logs is not supported by the QRdara.
The workflow may help us collect the G Mail logs from Google API.

Thanks

**Comment by ChrisCollinsIBM** [comment]
QRadar does have an integration with G-Suite for various Admin logs, but if this gets additional information we'd be happy to look at it. Did you submit a pull request?

**Comment by ChrisCollinsIBM** [comment]
Hi @Abrar729, when you have a workflow ready to submit please open a pull request as per the https://github.com/ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API/blob/master/CONTRIBUTING.md document. You can make a new issue when you are ready or re-open this one. Thank you.
