### ISSUE TITLE
Workflow for Mulesoft

### ISSUE THREAD

**Issue by adamdcameron** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#52]
I will be submitting a workflow and workflow parameter file to connect to Mulesoft's Cloud API.

**Comment by adamdcameron** [comment]
Useful links for reference:

https://help.mulesoft.com/s/article/How-to-get-Cloudhub-application-information-using-Anypoint-Platform-API


https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/cloudhub-api/minor/1.0/console/method/%233041/


https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/8617/versions/2321502/pages/107964

**Comment by ChrisCollinsIBM** [comment]
Hi @adamdcameron - I don't see a pull request for this one yet, still in process?

**Comment by adamdcameron** [comment]
I didn't even realize I had to complete that part.  I did have a talk with one of our documentation folks about this a while back, but I guess I didn't realize I had to take the next step.  I will submit the pull request now.

**Comment by ChrisCollinsIBM** [comment]
Not a problem! The pull request is how the actual workflow gets reviewed and merged in. 

Thanks!

**Comment by adamdcameron** [comment]
It seems this only works for Mulesoft CloudHub.  A customer tried to use this on Mulesoft Anypoint and it didn't work.  You can see some of the API doc here:  https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/audit-log-query-api/minor/1.0/console/documentation/%23151/

I helped the customer a little, but this API works differently.  It uses POST commands instead of GET and it doesn't seem to use a bookmark the way CloudHub does.  I had to sent them to Mulesoft support.  Hopefully they get back to me someday with that workflow so we can add it to.

All this to say, we should probably name this Workflow "Mulesoft CloudHub" specifically.

**Comment by ChrisCollinsIBM** [comment]
Sounds good, I'll keep an eye on the pull request for the updates. These are the types of details that greatly help others when trying to use the workflows and wondering if they are compatible with what they're trying to do or not. Thank you!
