### ISSUE TITLE
Not a JSON Array, timestamps in the payloads weeks old

### ISSUE THREAD

**Issue by matt-pb** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#57]
I have constructed an xml workflow for NS1 DNS. I am getting what appears to be real-time logs in json format.  However, the timestamps in the payloads (in epoch time) do not even come close to the Start time of the event as it shows in QRadar.  We have confirmed with the end users that the time in the payload is correct and not the Start time in QRadar.

I am following this for command line troubleshooting:

https://www.ibm.com/docs/en/dsm?topic=protocol-command-line-testing-tool

As we are using version 1, I have properly configured my command and am getting this output:

[ workflow]# java -cp "/opt/ibm/si/services/ecs-ec-ingress/current/bin/*:/opt/ibm/si/services/ecs-ec-ingress/eventgnosis/lib/q1labs/*" com.q1labs.semsources.sources.universalcloudrestapi.UniversalCloudRESTAPITest -wp Default-Workflow-Parameter-Values.xml -w qroc1.xml

SLF4J: Class path contains multiple SLF4J bindings.

SLF4J: Found binding in [jar:file:/opt/ibm/si/services/ecs-ec-ingress/2020.7.3.20210323172312/bin/slf4j-log4j12-1.7.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: Found binding in [jar:file:/opt/ibm/si/services/ecs-ec-ingress/2020.7.3.20210323172312/bin/slf4j-simple-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

2021-08-13 16:22:39 [INFO ][UniversalCloudRESTAPITest] Status changed to ERROR: Not a JSON Array: "<!doctype html>\n <html>\n <head>\n <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF8\">\n <title>NS1 | Customer Portal</title>\n <meta name=\"google\" content=\"notranslate\" />\n <script src=\"/cdn-cgi/apps/head/BGkBeDlUJpHx3swQRyf58HOAico.js\"></script><link rel=\"shortcut icon\" type=\"image/ico\" href=\"assets/favicon.ico\">\n <link href='//fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600|Open+Sans:300,600&amp;subset=latin' rel='stylesheet' type='text/css'>\n <link href=\"static/iconfont.css?v=<%= timestamp %>\" rel=\"stylesheet\" />\n </head>\n <body>\n\n <div id=\"app-body\"></div>\n <div id=\"error-modal\"></div>\n\n <script id=\"ga-script-holder\"></script>\n\n <script>\n (function(apiKey){\n (function(p,e,n,d,o){var v,w,x,y,z;o=p[d]=p[d]||{};o._q=o._q||[];\n v=['initialize','identify','updateOptions','pageLoad','track'];for(w=0,x=v.length;w<x;++w)(function(m){\n o[m]=o[m]||function(){o._q[m===v[0]?'unshift':'push']([m].concat([].slice.call(arguments,0)));};})(v[w]);\n y=e.createElement(n);y.async=!0;y.src='https://cdn.pendo.io/agent/static/'+apiKey+'/pendo.js';\n z=e.getElementsByTagName(n)[0];z.parentNode.insertBefore(y,z);})(window,document,'script','pendo');\n })('b2a55387-12c8-45ac-755d-dfc64dd9a22e');\n </script>\n <script src=\"ns1.js?v=1628794125638\"></script>\n <script>\n new NS1();\n </script>\n </body>\n </html>"

Again, I pass the tests and get real time logs in json format.  I just can't built use cases off of them as the time stamps are not correct.

I can provide the workflow.xml if necessary.

Thank you,

-Matt

**Comment by ChrisCollinsIBM** [comment]
Collecting events and parsing events are 2 completely separate processes. If the events are getting into QRadar as expected then I don't think it's an issue with the workflow rather with the Timestamp parsing in the Custom DSM.

If you could post a sanitized event sample with even just the relevant section to timestamp parsing and what you're using for an expression in the DSM editor we might be able to help out.

**Comment by matt-pb** [comment]
Hello!

Thanks for the reply!

We received the output of all events in the last week from NS1 as they see them.  We had less then 10 events.  This log source has an EPS of over 1.

It appears that the Workflow continually loops with or without a DoWhile statement.  I see the same payloads with the same meta data looping over and over again as a raw log.  This does not appear to be a parsing issue.

I have also used the command line testing tools and watch the same activity before it is processed and parsed.

NS1 offers a way to hard code the start and end request period in the GET statement.  I figured out the syntax for XML, however, both the start and end times would have to be a dynamic variable coded in the workflow for it to pull properly.  Perhaps I’m just not seeing it, but I don’t see any other Workflows on this site that use that logic.

Here is the Workflow:  (Note:  I have tried it with and without the DoWhile & if statements. It appears to loop without it judging from the cmd line output)

<?xml version="1.0" encoding="UTF-8" ?>

<Workflow name="NS1" version="1.0" xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/Workflow/V1">

	<Parameters>
       	<Parameter name="host" label="Host" required="true" />
		<Parameter name="auth_token" label="Authentication Token" required="true" />
	</Parameters> 

    <Actions>
	
	
		<CallEndpoint url="https://${/host}/v1/account/activity" method="GET" savePath="/get_logs/response">
			<SSLConfiguration allowUntrustedServerCertificate="true"/>		
			<RequestHeader name="X-NSONE-Key" value="${/auth_token}" />
			<RequestHeader name="Accept" value="text/html"/>		
		</CallEndpoint>
		
		<If condition="/get_logs/response/status_code != 200">
			<Abort reason="${/get_logs/body/response}" />
		</If>
		
			<PostEvents path="/get_logs/response/body" source="${/host}" />

    </Actions>

	<Tests>
       		<DNSResolutionTest host="${/host}" /> 
       		<TCPConnectionTest host="${/host}" /> 
       		<SSLHandshakeTest host="${/host}" />
 	</Tests> 

</Workflow>

Thank you,

-Matt

**Comment by Fa6s** [comment]
Hey Matt, 
i've just wrote such a workflow with dynamic start and end times: it is a [pull request currently](https://github.com/ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API/pull/67/commits/0133d8814f5258e62e17e3fb55ead22143beb5b0)

The magic happens here:
First if the workflow never ran before I set a start time which is today minus 24 hours.
```
<!-- set a startTime (today - 24 hours (86400000 ns) if the workflow runs for the first time on a system, if a startDateTime from a previous run already exists, skip and continue -->
		<If condition="empty(/startDateTime)" >
			<!-- Initialize the first startdatetime if not yet initialized with date which is current timestamp minus 24 hours (minus 864000000)  -->
			<Initialize path="/startDateTime" value="${time() - 86400000}" />
			<!-- Format date to work with the API -->
			<FormatDate pattern="yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" timeZone="UTC" time="${/startDateTime}" savePath="/startDateTime" />
		</If>
```
After that you want to set the endtime to the current time:
```
<!-- Format date to work with the Trend Micro Vision One API's date format -->
		<FormatDate pattern="yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" timeZone="UTC" time="${time()}" savePath="/endDateTime" />
```

Then I start my first GET request with the **start** and **enddatetime**:

```<!-- Pull Events from API -->
            <CallEndpoint url="https://${/hostURL}/v2.0/siem/events" method="GET" savePath="/get_events_alertList/response">
                <BearerAuthentication token="${/baerer_token}"/>
				<QueryParameter name="startDateTime" value="${/startDateTime}" />
				<QueryParameter name="endDateTime" value="${/endDateTime}" />
				<RequestHeader name="contentType" value="'Content-Type': 'application/json;charset=utf-8'" />
			</CallEndpoint>
```

Then after the workflow ran successfully I set the startdatetime with the current enddatetime so that for whenever the next run is, the startdate is fixed with the date of the last successful run (this is because the value remains in the "state" until changed thus you could suffer a QRadar outage for three days and after that (if the "state" remained untouched) your next pull will start with time the workflow ran the last time before the outage):
```
<!-- Set new startDateTime as last run EndDateTime after successful run to save the last run end for the next run as new startDateTime  -->
		<Set path="/startDateTime" value="${/endDateTime}" />
```



let me know if anything is not clear to you so I can explain to you in detail

- Fabian

**Comment by ChrisCollinsIBM** [comment]
Seems like this question has been addressed and some feedback given, please re-open this issue if further assistance is required.
