### ISSUE TITLE
Special char notation for workflow passwords

### ISSUE THREAD

**Issue by hcrisgnya** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#64]
We are looking for the correct notation/format of special char in passwords.

    <Value name="password" value="lleHo&wrlod" />

^^^^This won't work!

We assume HTML notation for instance. For example, it means "lleHo&wrlod" and now this will be brought to "lleHo&amp;wrlod" ?

    <Value name="password" value="lleHo&amp;wrlod" />
& = '& a m p;'

**Comment by Dak0ta** [comment]
The workflow and parameter files are XML, so @Fa6s is correct you'd need to make sure anything in there is XML-safe for a value.

Most things would be fine however except a double quote `"` and the ampersand `&`.
