### ISSUE TITLE
Add workflow for Trend Micro Vision One API

### ISSUE THREAD

**Issue by Fa6s** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#66]
New workflow for Trend Micro Vision One product to pull alert events from its API.
Used APIs:
https://automation.trendmicro.com/xdr/api-v2#tag/Alerts/paths/~1v2.0~1siem~1events/get
https://automation.trendmicro.com/xdr/api-v2#tag/Details/paths/~1v2.0~1xdr~1workbench~1workbenches~1{workbenchId}/get

**Comment by Jopinder** [comment]
Yes please. We are stuck using Syslog over TLS to get the logs and we see a big difference in the quality of data we get there vs what we should be able to get via the API.
