### ISSUE TITLE
Zoom logs, large discrepency

### ISSUE THREAD

**Issue by bryanscu** [ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API#69]
Previously successfully set up DUO logs which work as expected.

Did the same for Zoom, and I get a very small handful of logs compared to what is in the zoom admin gui.  We have fairly constant zoom logs throughout the day, but I'll get maybe 5-10 logs a day, vs the 2000 or so we actually have.

Protocol test works.  Command line testing tool works.  Coalescing is not turned on for the log source.

**Comment by ChrisCollinsIBM** [comment]
Hey @bryanscu, at a glance that workflow looks like a good sample of how to connect to Zoom, but it doesn't appear to be a complete "production-ready" solution.

The main thing I don't see is any handling for paging, the Zoom API definitely mentions paging tokens which would require a DoWhile loop or something similar to handle.

https://marketplace.zoom.us/docs/api-reference/zoom-api/reports/reportsigninsignoutactivities

**Comment by ChrisCollinsIBM** [comment]
Haven't heard back on this one, so I'll close it out for now.

Please re-open if you'd like to continue the discussion further. Thanks!
